FROM python:3.12-slim

WORKDIR /app

COPY requirements-frontend.txt .

RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY frontend ./frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/ui.py", "--server.address=0.0.0.0"]