FROM python:3.12-slim

WORKDIR /app

COPY requirements-backend.txt .

RUN pip install --no-cache-dir -r requirements-backend.txt

COPY backend ./backend

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0"]